fos_rest:
  param_fetcher_listener:  force
  disable_csrf_role: ROLE_API
  view:
    view_response_listener:  true
  body_converter:
      enabled: true
      validate: true
      validation_errors_argument: validationErrors # This is the default value
  allowed_methods_listener:  true
  format_listener:
      rules:
          - { path: '^/api/', prefer_extension: true, fallback_format: json, priorities: [ 'json'] }
