controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: api

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_refresh_token:
    path: /api/token/refresh

api_login_check:
    path: /api/login

api_token_invalidate:
    path: /api/token/invalidate
    
